---
- name: Client sample task
  debug:
    msg: "Ansible is executing configure-client.yml file..."

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install NFS common
  apt:
    name: nfs-common
    state: present

- name: Create Mount directory
  file:
    path: "{{ client_shared_dir }}"
    state: directory
    mode: 0755

- name: Set ownership of the directory
  file:
    path: "{{ client_shared_dir }}"
    owner: "{{ shared_user }}"
    group: "{{ shared_group }}"
    recurse: yes

- name: Mount NFS share
  become: yes
  shell: "mount {{ host_ip }}:{{ host_shared_dir }} {{ client_shared_dir }}"

- name: Add NFS entry to /etc/fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    line: "{{ host_ip }}:{{ host_shared_dir }}    {{ client_shared_dir }}   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"
    create: yes

- name: Test the NFS Mount
  command: touch {{ client_shared_dir }}/client.test
